name: manage-azure-policy-24681f67
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**'
#      - 'policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**'
#      - 'policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**'
#      - 'initiatives/Deploy_Azure_Security_Center_configuration_Deploy-ASC-Config/**'
#      - 'initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**'
#      - 'initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**'
#      - 'initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**'
#      - 'initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**'
#      - .github/workflows/manage-azure-policy-24681f67.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_24681f67}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**
          policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**
          policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**
          initiatives/Deploy_Azure_Security_Center_configuration_Deploy-ASC-Config/**
          initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**
          initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**
          initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**
          initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**
